### ISSUE TITLE
镜像编译报错

### ISSUE THREAD

**Issue by zhaohainan666** [neursafe/federated-learning#22]
按照文档给的方法，做镜像时报错， 日志如下：
          Build NeurSafe FL all images.
          ------------Build nsfl-base:latest----------------
          Sending build context to Docker daemon  3.994MB
          Step 1/6 : FROM python:3.7.8
           ---> d70fc156eb55
          Step 2/6 : COPY deploy/scripts/install_bazel.sh /tmp/install_bazel.sh
           ---> Using cache
           ---> 3b8509353a39
          Step 3/6 : RUN bash /tmp/install_bazel.sh &&     rm -f /tmp/install_bazel.sh
           ---> Running in 2140051bb7df
          Bazel installer
          ---------------
          
          Bazel is bundled with software licensed under the GPLv2 with Classpath exception.
          You can find the sources next to the installer on our release page:
             https://github.com/bazelbuild/bazel/releases
          
          # 
          
          ## Build information
             - [Commit](https://github.com/bazelbuild/bazel/commit/76cc17f)
          Uncompressing.......
          
          Bazel is now installed!
          
          Make sure you have "/usr/local/bin" in your path. You can also activate bash
          completion by adding the following line to your ~/.bashrc:
            source /usr/local/lib/bazel/bin/bazel-complete.bash
          
          See http://bazel.build/docs/getting-started.html to start a new project!
          /
          Removing intermediate container 2140051bb7df
           ---> b90e69acac42
          Step 4/6 : COPY requirements.txt /tmp/neursafe_fl/requirements.txt
           ---> 86480b6e4ba4
          Step 5/6 : SHELL ["/bin/bash", "-c"]
           ---> Running in 66b34cb54ea6
          Removing intermediate container 66b34cb54ea6
           ---> 270f8645bcce
          Step 6/6 : RUN python3.7 -m pip install -r /tmp/neursafe_fl/requirements.txt &&         rm -rf ~/.cache/pip /tmp/neursafe_fl
           ---> Running in 261cab5ae3d4
          Collecting click==7.1.2
            Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
          Collecting urllib3==1.26.4
            Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
          Collecting absl-py==0.11.0
            Downloading absl_py-0.11.0-py3-none-any.whl (127 kB)
          Collecting boto3==1.17.67
            Downloading boto3-1.17.67-py2.py3-none-any.whl (131 kB)
          Collecting cryptography==3.3.1
            Downloading cryptography-3.3.1-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
          Collecting lmdb==1.0.0
            Downloading lmdb-1.0.0-cp37-cp37m-manylinux1_x86_64.whl (280 kB)
          Collecting grpclib==0.4.1
            Downloading grpclib-0.4.1.tar.gz (57 kB)
            Installing build dependencies: started
            Installing build dependencies: finished with status 'done'
            Getting requirements to build wheel: started
            Getting requirements to build wheel: finished with status 'done'
              Preparing wheel metadata: started
              Preparing wheel metadata: finished with status 'done'
          Collecting protobuf==3.14.0
            Downloading protobuf-3.14.0-cp37-cp37m-manylinux1_x86_64.whl (1.0 MB)
          Collecting tensorflow==2.4.0
            Downloading tensorflow-2.4.0-cp37-cp37m-manylinux2010_x86_64.whl (394.7 MB)
          
          Collecting cgroupspy==0.1.6
            Downloading cgroupspy-0.1.6.tar.gz (14 kB)
          Collecting watchdog==0.10.3
            Downloading watchdog-0.10.3.tar.gz (94 kB)
          Collecting torch==1.7.1
            Downloading torch-1.7.1-cp37-cp37m-manylinux1_x86_64.whl (776.8 MB)
          
          
          Collecting torchvision==0.8.2
            Downloading torchvision-0.8.2-cp37-cp37m-manylinux1_x86_64.whl (12.8 MB)
          Collecting nvidia-ml-py==11.450.51
            Downloading nvidia-ml-py-11.450.51.tar.gz (23 kB)
          Collecting diffiehellman==0.13.3
            Downloading diffiehellman-0.13.3.tar.gz (5.3 kB)
          Collecting secret-sharing==0.2.7
            Downloading secret-sharing-0.2.7.tar.gz (6.3 kB)
          Collecting kubernetes==12.0.1
            Downloading kubernetes-12.0.1-py2.py3-none-any.whl (1.7 MB)
          Collecting psutil==5.8.0
            Downloading psutil-5.8.0-cp37-cp37m-manylinux2010_x86_64.whl (296 kB)
          Collecting tornado==6.1
            Downloading tornado-6.1-cp37-cp37m-manylinux2010_x86_64.whl (428 kB)
          Collecting pymongo==3.11.3
            Downloading pymongo-3.11.3-cp37-cp37m-manylinux2014_x86_64.whl (512 kB)
          Collecting psycopg2==2.7.7
            Downloading psycopg2-2.7.7-cp37-cp37m-manylinux1_x86_64.whl (2.7 MB)
          Collecting pycryptodome==3.10.1
            Downloading pycryptodome-3.10.1-cp35-abi3-manylinux2010_x86_64.whl (1.9 MB)
          Collecting pyOpenSSL==20.0.1
            Downloading pyOpenSSL-20.0.1-py2.py3-none-any.whl (54 kB)
          Collecting six
            Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
          Collecting jmespath<1.0.0,>=0.7.1
            Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
          Collecting s3transfer<0.5.0,>=0.4.0
            Downloading s3transfer-0.4.2-py2.py3-none-any.whl (79 kB)
          Collecting botocore<1.21.0,>=1.20.67
            Downloading botocore-1.20.112-py2.py3-none-any.whl (7.7 MB)
          Collecting cffi>=1.12
            Downloading cffi-1.15.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (427 kB)
          Collecting h2<5,>=3.1.0
            Downloading h2-4.1.0-py3-none-any.whl (57 kB)
          Collecting multidict
            Downloading multidict-6.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (94 kB)
          Collecting astunparse~=1.6.3
            Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
          Collecting termcolor~=1.1.0
            Downloading termcolor-1.1.0.tar.gz (3.9 kB)
          Collecting keras-preprocessing~=1.1.2
            Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
          Collecting numpy~=1.19.2
            Downloading numpy-1.19.5-cp37-cp37m-manylinux2010_x86_64.whl (14.8 MB)
          Collecting wheel~=0.35
            Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
          Collecting gast==0.3.3
            Downloading gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
          Collecting flatbuffers~=1.12.0
            Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
          Collecting tensorflow-estimator<2.5.0,>=2.4.0rc0
            Downloading tensorflow_estimator-2.4.0-py2.py3-none-any.whl (462 kB)
          Collecting google-pasta~=0.2
            Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
          Collecting tensorboard~=2.4
            Downloading tensorboard-2.9.1-py3-none-any.whl (5.8 MB)
          Collecting typing-extensions~=3.7.4
            Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
          Collecting opt-einsum~=3.3.0
            Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
          Collecting grpcio~=1.32.0
            Downloading grpcio-1.32.0-cp37-cp37m-manylinux2014_x86_64.whl (3.8 MB)
          Collecting h5py~=2.10.0
            Downloading h5py-2.10.0-cp37-cp37m-manylinux1_x86_64.whl (2.9 MB)
          Collecting wrapt~=1.12.1
            Downloading wrapt-1.12.1.tar.gz (27 kB)
          Collecting pathtools>=0.1.1
            Downloading pathtools-0.1.2.tar.gz (11 kB)
          Collecting pillow>=4.1.1
            Downloading Pillow-9.1.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
          Collecting utilitybelt
            Downloading utilitybelt-0.2.6.tar.gz (3.9 kB)
          Collecting certifi>=14.05.14
            Downloading certifi-2022.5.18.1-py3-none-any.whl (155 kB)
          Collecting websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0
            Downloading websocket_client-1.3.2-py3-none-any.whl (54 kB)
          Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.7/site-packages (from kubernetes==12.0.1->-r /tmp/neursafe_fl/requirements.txt (line 18)) (49.3.1)
          Collecting python-dateutil>=2.5.3
            Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
          Collecting google-auth>=1.0.1
            Downloading google_auth-2.7.0-py2.py3-none-any.whl (160 kB)
          Collecting requests
            Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
          Collecting pyyaml>=3.12
            Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
          Collecting requests-oauthlib
            Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
          Collecting pycparser
            Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
          Collecting hpack<5,>=4.0
            Downloading hpack-4.0.0-py3-none-any.whl (32 kB)
          Collecting hyperframe<7,>=6.0
            Downloading hyperframe-6.0.1-py3-none-any.whl (12 kB)
          Collecting tensorboard-data-server<0.7.0,>=0.6.0
            Downloading tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
          Collecting google-auth-oauthlib<0.5,>=0.4.1
            Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
          Collecting markdown>=2.6.8
            Downloading Markdown-3.3.7-py3-none-any.whl (97 kB)
          Collecting werkzeug>=1.0.1
            Downloading Werkzeug-2.1.2-py3-none-any.whl (224 kB)
          Collecting tensorboard-plugin-wit>=1.6.0
            Downloading tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
          Collecting pyasn1-modules>=0.2.1
            Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
          Collecting rsa<5,>=3.1.4; python_version >= "3.6"
            Downloading rsa-4.8-py3-none-any.whl (39 kB)
          Collecting cachetools<6.0,>=2.0.0
            Downloading cachetools-5.2.0-py3-none-any.whl (9.3 kB)
          Collecting charset-normalizer~=2.0.0; python_version >= "3"
            Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
          Collecting idna<4,>=2.5; python_version >= "3"
            Downloading idna-3.3-py3-none-any.whl (61 kB)
          Collecting oauthlib>=3.0.0
            Downloading oauthlib-3.2.0-py3-none-any.whl (151 kB)
          Collecting importlib-metadata>=4.4; python_version < "3.10"
            Downloading importlib_metadata-4.11.4-py3-none-any.whl (18 kB)
          Collecting pyasn1<0.5.0,>=0.4.6
            Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
          Collecting zipp>=0.5
            Downloading zipp-3.8.0-py3-none-any.whl (5.4 kB)
          Building wheels for collected packages: grpclib, cgroupspy, watchdog, nvidia-ml-py, diffiehellman, secret-sharing, termcolor, wrapt, pathtools, utilitybelt
            Building wheel for grpclib (PEP 517): started
            Building wheel for grpclib (PEP 517): finished with status 'done'
            Created wheel for grpclib: filename=grpclib-0.4.1-py3-none-any.whl size=69834 sha256=8f1fa9c232c90da7d272f23f591fa3e1365471871814382d8f167565553b2621
            Stored in directory: /root/.cache/pip/wheels/24/dc/d4/6f5f1421c630f0d59a00e3f6061ebd78389ec8da08913baa4a
            Building wheel for cgroupspy (setup.py): started
            Building wheel for cgroupspy (setup.py): finished with status 'done'
            Created wheel for cgroupspy: filename=cgroupspy-0.1.6-py3-none-any.whl size=17887 sha256=8d4c650b127f20eec1c39429ca0ca2c7bfc4aa1ffa8918d890edd12abd8013d1
            Stored in directory: /root/.cache/pip/wheels/6b/8e/89/f93dc69d26c2bba667b1615ffd0bb0f91b977ec59cf9e19fa8
            Building wheel for watchdog (setup.py): started
            Building wheel for watchdog (setup.py): finished with status 'done'
            Created wheel for watchdog: filename=watchdog-0.10.3-py3-none-any.whl size=73871 sha256=4ecbbb793d124910ce65fb3f2573d1ee9f26ad8745771ee9b20806eec85d785e
            Stored in directory: /root/.cache/pip/wheels/27/21/35/9d1e531f9de5335147dbef07e9cc99d312525ba128a93d1225
            Building wheel for nvidia-ml-py (setup.py): started
            Building wheel for nvidia-ml-py (setup.py): finished with status 'done'
            Created wheel for nvidia-ml-py: filename=nvidia_ml_py-11.450.51-py3-none-any.whl size=24232 sha256=c00c3bfa8f3b3921274203d2574c8bb0ff4a45ba179cd98ff5229e4f607bc336
            Stored in directory: /root/.cache/pip/wheels/b3/69/f5/6e7f8d6e3a0dbbe4db51449bf1e243a7486f43b4f344b38b8d
            Building wheel for diffiehellman (setup.py): started
            Building wheel for diffiehellman (setup.py): finished with status 'done'
            Created wheel for diffiehellman: filename=diffiehellman-0.13.3-py3-none-any.whl size=7364 sha256=0aa386ff6559f7e259975900b38df36ec49c9ae22bf418b53bcf8215445220da
            Stored in directory: /root/.cache/pip/wheels/d4/99/da/b971b9b0fb6fe78fbf1f5e1b1c4780ff68b22ade247138d7b0
            Building wheel for secret-sharing (setup.py): started
            Building wheel for secret-sharing (setup.py): finished with status 'done'
            Created wheel for secret-sharing: filename=secret_sharing-0.2.7-py3-none-any.whl size=5745 sha256=09f43b224d7244bf7cbe66b4089e63da0aaed29d7589e640cf0ae9cae5b98bd8
            Stored in directory: /root/.cache/pip/wheels/08/9e/b5/738fd7420cff4bdd74e72c2b8d9262c4be579e5022ec733475
            Building wheel for termcolor (setup.py): started
            Building wheel for termcolor (setup.py): finished with status 'done'
            Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4830 sha256=6da1764c176884dbe83ed47eb210b728fded4b4edb94ba3de330bada9d740612
            Stored in directory: /root/.cache/pip/wheels/3f/e3/ec/8a8336ff196023622fbcb36de0c5a5c218cbb24111d1d4c7f2
            Building wheel for wrapt (setup.py): started
            Building wheel for wrapt (setup.py): finished with status 'done'
            Created wheel for wrapt: filename=wrapt-1.12.1-cp37-cp37m-linux_x86_64.whl size=76417 sha256=51707a7779760e891a351d2fc597a903b9037b5f3ba700281c55c877f5b272c6
            Stored in directory: /root/.cache/pip/wheels/62/76/4c/aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6
            Building wheel for pathtools (setup.py): started
            Building wheel for pathtools (setup.py): finished with status 'done'
            Created wheel for pathtools: filename=pathtools-0.1.2-py3-none-any.whl size=8784 sha256=29c6fab5b554144a0e52d994d99fbf042f95d7339ef8ed7034a6efb69ce8b1a0
            Stored in directory: /root/.cache/pip/wheels/3e/31/09/fa59cef12cdcfecc627b3d24273699f390e71828921b2cbba2
            Building wheel for utilitybelt (setup.py): started
            Building wheel for utilitybelt (setup.py): finished with status 'done'
            Created wheel for utilitybelt: filename=utilitybelt-0.2.6-py3-none-any.whl size=5581 sha256=7000a8f09d4112435c67f8ccc323d018cbf06551c35b23712b39084bb0eb1ee4
            Stored in directory: /root/.cache/pip/wheels/fe/4e/71/1930807859723c55b0ee510e636a745dea2abea10ebf97c06f
          Successfully built grpclib cgroupspy watchdog nvidia-ml-py diffiehellman secret-sharing termcolor wrapt pathtools utilitybelt
          Installing collected packages: click, urllib3, six, absl-py, jmespath, python-dateutil, botocore, s3transfer, boto3, pycparser, cffi, cryptography, lmdb, hpack, hyperframe, h2, multidict, grpclib, protobuf, wheel, astunparse, termcolor, numpy, keras-preprocessing, gast, flatbuffers, tensorflow-estimator, google-pasta, tensorboard-data-server, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, oauthlib, charset-normalizer, idna, certifi, requests, requests-oauthlib, google-auth-oauthlib, zipp, typing-extensions, importlib-metadata, markdown, werkzeug, tensorboard-plugin-wit, grpcio, tensorboard, opt-einsum, h5py, wrapt, tensorflow, cgroupspy, pathtools, watchdog, torch, pillow, torchvision, nvidia-ml-py, diffiehellman, utilitybelt, secret-sharing, websocket-client, pyyaml, kubernetes, psutil, tornado, pymongo, psycopg2, pycryptodome, pyOpenSSL
            Attempting uninstall: wheel
              Found existing installation: wheel 0.34.2
              Uninstalling wheel-0.34.2:
                Successfully uninstalled wheel-0.34.2
          ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
          
          We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
          
          tensorflow 2.4.0 requires six~=1.15.0, but you'll have six 1.16.0 which is incompatible.
          Successfully installed absl-py-0.11.0 astunparse-1.6.3 boto3-1.17.67 botocore-1.20.112 cachetools-5.2.0 certifi-2022.5.18.1 cffi-1.15.0 cgroupspy-0.1.6 charset-normalizer-2.0.12 click-7.1.2 cryptography-3.3.1 diffiehellman-0.13.3 flatbuffers-1.12 gast-0.3.3 google-auth-2.7.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.32.0 grpclib-0.4.1 h2-4.1.0 h5py-2.10.0 hpack-4.0.0 hyperframe-6.0.1 idna-3.3 importlib-metadata-4.11.4 jmespath-0.10.0 keras-preprocessing-1.1.2 kubernetes-12.0.1 lmdb-1.0.0 markdown-3.3.7 multidict-6.0.2 numpy-1.19.5 nvidia-ml-py-11.450.51 oauthlib-3.2.0 opt-einsum-3.3.0 pathtools-0.1.2 pillow-9.1.1 protobuf-3.14.0 psutil-5.8.0 psycopg2-2.7.7 pyOpenSSL-20.0.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.21 pycryptodome-3.10.1 pymongo-3.11.3 python-dateutil-2.8.2 pyyaml-6.0 requests-2.27.1 requests-oauthlib-1.3.1 rsa-4.8 s3transfer-0.4.2 secret-sharing-0.2.7 six-1.16.0 tensorboard-2.9.1 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-2.4.0 tensorflow-estimator-2.4.0 termcolor-1.1.0 torch-1.7.1 torchvision-0.8.2 tornado-6.1 typing-extensions-3.7.4.3 urllib3-1.26.4 utilitybelt-0.2.6 watchdog-0.10.3 websocket-client-1.3.2 werkzeug-2.1.2 wheel-0.37.1 wrapt-1.12.1 zipp-3.8.0
          WARNING: You are using pip version 20.2.2; however, version 22.1.2 is available.
          You should consider upgrading via the '/usr/local/bin/python3.7 -m pip install --upgrade pip' command.
          Removing intermediate container 261cab5ae3d4
           ---> bc88ac4d0af4
          Successfully built bc88ac4d0af4
          Successfully tagged nsfl-base:latest
          --------Build or push nsfl-base:latest Successfully-------
          ------------Build 10.233.172.2:5000/nsfl-cli:latest----------------
          Sending build context to Docker daemon  3.994MB
          Step 1/6 : FROM nsfl-base:latest
           ---> bc88ac4d0af4
          Step 2/6 : ARG FL_PROJECT_PATH=/tmp/neursafe_fl
           ---> Running in 2b7411ca9e93
          Removing intermediate container 2b7411ca9e93
           ---> c8dc26ee4e5a
          Step 3/6 : COPY . ${FL_PROJECT_PATH}
           ---> a82deb605bf0
          Step 4/6 : RUN . ${FL_PROJECT_PATH}/deploy/scripts/const.properties &&     cd ${FL_PROJECT_PATH} &&     bazel build $cli_bazel_obj &&     cd -
           ---> Running in c01814c42655
          Extracting Bazel installation...
          Starting local Bazel server and connecting to it...
          Loading: 
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          Loading: 0 packages loaded
          INFO: Repository rules_python instantiated at:
            no stack (--record_rule_instantiation_callstack not enabled)
          Repository rule git_repository defined at:
            /root/.cache/bazel/_bazel_root/86292729879514e3c2b25f87138800ba/external/bazel_tools/tools/build_defs/repo/git.bzl:195:33: in <toplevel>
          ERROR: An error occurred during the fetch of repository 'rules_python':
             Traceback (most recent call last):
	          File "/root/.cache/bazel/_bazel_root/86292729879514e3c2b25f87138800ba/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177, column 30, in _git_repository_implementation
		          update = _clone_or_update(ctx)
	          File "/root/.cache/bazel/_bazel_root/86292729879514e3c2b25f87138800ba/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
		          git_ = git_repo(ctx, directory)
	          File "/root/.cache/bazel/_bazel_root/86292729879514e3c2b25f87138800ba/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		          _update(ctx, git_repo)
	          File "/root/.cache/bazel/_bazel_root/86292729879514e3c2b25f87138800ba/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, column 10, in _update
		          fetch(ctx, git_repo)
	          File "/root/.cache/bazel/_bazel_root/86292729879514e3c2b25f87138800ba/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 129, column 27, in fetch
		          _git_maybe_shallow(
	          File "/root/.cache/bazel/_bazel_root/86292729879514e3c2b25f87138800ba/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 171, column 15, in _git_maybe_shallow
		          _error(ctx.name, start + args_list, st.stderr)
	          File "/root/.cache/bazel/_bazel_root/86292729879514e3c2b25f87138800ba/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 182, column 9, in _error
		          fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
          Error in fail: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @rules_python:
          Timed out
          ERROR: no such package '@rules_python//python': error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @rules_python:
          Timed out
          INFO: Elapsed time: 608.932s
          INFO: 0 processes.
          FAILED: Build did NOT complete successfully (0 packages loaded)
          FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by zhaohainan666** [comment]
网络问题，重试一遍之后可以了

**Comment by ChengMingZhang-ZTE** [comment]
problem solved

**Comment by ChengMingZhang-ZTE** [comment]
problem solved
