### ISSUE TITLE
使用kubernetes部署时 pg 数据库和 mongo 数据库没有容器化

### ISSUE THREAD

**Issue by zhaohainan666** [neursafe/federated-learning#31]
使用kubernetes 部署时，pg数据库和mongo数据库没有容器化安装方法，只给了各自的官方指导文档，不方便用户的安装，增加了安装难度

**Comment by tangbo-sh** [comment]
The service of database is a very complex issue. How to ensure its HA, containerization is not necessarily the best choice. It is not recommended to give containerization as a standardized installation.

**Comment by tangbo-sh** [comment]
Database installation is a standard process, please refer to the corresponding official documentation.
