### ISSUE TITLE
data server 支持标准的S3接口，不局限minio

### ISSUE THREAD

**Issue by zhaohainan666** [neursafe/federated-learning#46]
data server支持标准的S3接口，不局限minio

**Comment by kewenwang-ai** [comment]
Minio follow the s3 standard interface.  In the code, whether to mount the buckets to local filesystem  or nsfl-ctl upload files to server，both follow the s3 interface, not restricted in minio. You can set the url(endpoint) with other s3 service, such as Amazon s3 service.
