### ISSUE TITLE
Coordinator saved checkponints directory index is not correct

### ISSUE THREAD

**Issue by ChengMingZhang-ZTE** [neursafe/federated-learning#88]
There is a correlation between the checkpoint folder numbers saved by different federation jobs

![image](https://user-images.githubusercontent.com/54432992/191404956-c562c266-3533-4f0c-88d3-78f6cb36c471.png)

**Comment by kewenwang-ai** [comment]
**/job_name_V\*\*\*/checkpoints/chekpoint_v\*\*\*(ckpt_id)/checkpoint_\*\*\*(round_id)**
Every time the job is executed, there will be a working directory, which is, **job_tf-mnist_output_V\*\*\*,** and then there is a **checkpoints** directory under this directory to store the intermediate checkpoints.

The ckpt id is shared in multiple version directories of the job, and the new execution will start after the last final checkpoint version number. For example, the last execution of job saves checkpoint_v6, then the next task execution will start from checkpoint_v7 start. even in different job working directory.

The last part of the filename is only round_id, which indicates the current round number when it was saved, and has nothing to do with the above ckpt_id.
